### ISSUE TITLE
Jbehave-to-Gherkin.jar not running 

### ISSUE THREAD

**Issue by murthysp** [seize-the-dave/jbehave-to-gherkin#10]
I tried running with the following command and new feature file was not generated

C:\StoryConverter>java -jar jbehave-to-gherkin.jar jbehave.story cucumber.feature

**Comment by murthysp** [comment]
From the UI getting the following Error

**Comment by murthysp** [comment]
From the UI getting the following error 
-------------------------------------------------------------------------------
Test set: uk.co.adaptivelogic.jbehavetogherkin.ConverterIT
-------------------------------------------------------------------------------
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.13 sec <<< FAILURE! - in uk.co.adaptivelogic.jbehavetogherkin.ConverterIT
shouldTranslateNarrativeToFeature(uk.co.adaptivelogic.jbehavetogherkin.ConverterIT)  Time elapsed: 0.021 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: "@meta\r\nFeature: Gherkin feature description\r\n  In order to use Cucumber\r\n  As a business analyst\r\n  I want to convert my JBehave to Gherkin\r\n\r\n  Background:\r\n    Given I am a before step\r\n\r\n  @scenario-meta\r\n  Scenario: Gherkin scenario description\r\n    Given I have some JBehave stories\r\n\r\n      | name  | rank     |\r\n      | Larry | Stooge 3 |\r\n      | Moe   | Stooge 1 |\r\n      | Curly | Stooge 2 |\r\n    When I execute jbehave-to-gherkin\r\n    Then I should have Gherkin features\r\n\r\n  @author-joe-bloggs\r\n  Scenario Outline: Second scenario\r\n    Given a [precondition] has occurred\r\n    When an action is performed\r\n    Then a [postcondition] should occur\r\n\r\n    Examples:\r\n      | precondition | postcondition |\r\n      | foo          | bar           |\r\n"
     but: was "@meta\nFeature: Gherkin feature description\n  In order to use Cucumber\n  As a business analyst\n  I want to convert my JBehave to Gherkin\n\n  Background: \n    Given I am a before step\n\n  @scenario-meta\n  Scenario: Gherkin scenario description\n    Given I have some JBehave stories\r\n\n      | name  | rank     |\n      | Larry | Stooge 3 |\n      | Moe   | Stooge 1 |\n      | Curly | Stooge 2 |\n    When I execute jbehave-to-gherkin\n    Then I should have Gherkin features\n\n  @author-joe-bloggs\n  Scenario Outline: Second scenario\n    Given a [precondition] has occurred\n    When an action is performed\n    Then a [postcondition] should occur\n\n    Examples: \n      | precondition | postcondition |\n      | foo          | bar           |\n"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at uk.co.adaptivelogic.jbehavetogherkin.ConverterIT.shouldTranslateNarrativeToFeature(ConverterIT.java:63)

**Comment by murthysp** [comment]
working fine.
